name: Deploy to Server

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout репозитория
        uses: actions/checkout@v4

      - name: Установка SSH-ключа
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Деплой на сервер
        run: |
          ssh -o StrictHostKeyChecking=no root@194.87.74.60 << 'EOF'
            cd /var/www/html
            git pull origin main
            sudo systemctl restart nginx  # Перезапуск Nginx
          EOF
